stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build

sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonarqube
  dependencies:
    - test


deploy:
  stage: deploy
  script:
    - "./gradlew shadowJar"
    - "docker build -t bookyapp:5.0 ."
  dependencies:
    - sonarqube


