stages:
  - build
  - test
  - sonarqube

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build

sonarqube:
  stage: sonarqube
    script:
      - ./gradlew sonarqube
    dependencies:
      - test


